name: Generate Snake

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # execute every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg
