name: Generate Data

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: iLukSbr/snk@main
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg
