name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # execute every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create snake
        uses: iLukSbr/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg
          
      - name: Save snake
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
